apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /my-busybox-deployment
  name: my-busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1.33.0 # kpt-set: ${image}:${tag}
          command:
            - sleep
            - "3600"
